name: finsem_org
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10
  cloud_functions: ^3.2.10
  firebase_auth: ^3.3.10
  google_sign_in: ^5.2.4
  google_fonts: ^2.3.1
  flutter_screenutil: ^5.3.1
  fluttertoast: ^8.0.9
  get: ^4.6.1
  firebase_app_check: ^0.0.6+7
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.2
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    #- assets/vectors/
    - assets/icons/
    - assets/images/
